# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQBVDs3hy3jH5sr-DpZ-tBSx-cEBPN9U
"""

# this is a chatbot program

#import the library
from nltk.chat.util import Chat ,reflections

tags =[
        ['my name is  (.*)' , ['hi  %1']],
        ['(hi|hello|hola|hey)' , ['hey there wassup', 'hi there' ,'hola ']],
       ['how you doing' ,['i am doing great', 'amazing' , 'not bad']],
        ['how is the weather in (.*)' , ['the weather in %1 is amazing']],
        ['(.*)help(.*)' , ['i can help you ']],
       ['thank you',[ 'you are welcome']],
       ['(.*)  in  (.*)  is fun' ,[' %1  in %2   was indeed fun']],
        ['(.*) your name ?' ,['my name is klaus mikhaelson']]
        ]

my_dummy_reflections ={
    'go' : 'gone',
    'hello'  :  'hey there'
    'wassup' : 'nothing great'
     
    }

chat = Chat(pairs , my_dummy_reflections)
#chat._substitute('go')
chat.converse()



